"""Emit normalized schemas as Pydantic v2 model declarations."""

from openapi_pyx.codegen.nodes import (
    Import,
    ImportFrom,
    ModelField,
    Module,
    PydanticModel,
    Stmt,
    TypeAlias,
    TypeExpr,
)
from openapi_pyx.ir.schema import (
    ArraySchema,
    DiscriminatedUnion,
    FreeFormSchema,
    NamedSchema,
    NamedSchemaRef,
    ObjectSchema,
    PrimitiveSchema,
    Schema,
    TaggedUnion,
)
from openapi_pyx.naming import field_name, model_name

_PRIMITIVE_PY = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
    "null": "None",
}


class _ModuleImports:
    __slots__ = ("annotated", "any", "config_dict", "discriminator", "field", "literal")

    def __init__(self) -> None:
        self.annotated = False
        self.any = False
        self.config_dict = False
        self.discriminator = False
        self.field = False
        self.literal = False


def emit_models_module(schemas: list[NamedSchema]) -> Module:
    flags = _ModuleImports()
    body: list[Stmt] = [_emit_named_schema(ns, flags) for ns in schemas]
    return Module(
        docstring="Generated by openapi-pyx. Do not edit by hand.",
        imports=_build_imports(flags),
        body=body,
    )


def _emit_named_schema(ns: NamedSchema, flags: _ModuleImports) -> Stmt:
    s = ns.schema
    cls_name = model_name(ns.name)

    if isinstance(s, ObjectSchema):
        fields, fi = _emit_object_fields(s)
        extra = "allow" if s.additional_properties == "any" else None
        populate_by_name = any(f.serialization_alias is not None for f in fields)
        flags.field = flags.field or fi.field
        flags.any = flags.any or fi.any
        flags.literal = flags.literal or fi.literal
        flags.config_dict = flags.config_dict or extra is not None or populate_by_name
        return PydanticModel(
            name=cls_name,
            fields=fields,
            docstring=ns.description,
            extra=extra,
            populate_by_name=populate_by_name,
        )
    if isinstance(s, DiscriminatedUnion):
        flags.annotated = True
        flags.discriminator = True
        return _emit_discriminated_union_alias(cls_name, s)

    rendered = _render_tagged_union(s) if isinstance(s, TaggedUnion) else _render_type(s)
    if "Literal[" in rendered:
        flags.literal = True

    constraints = s.constraints if isinstance(s, PrimitiveSchema) else {}
    has_metadata = ns.description is not None or bool(ns.examples) or bool(constraints)
    if has_metadata:
        flags.annotated = True
        flags.field = True
        rendered = _wrap_with_field(rendered, ns, constraints)
    return TypeAlias(name=cls_name, value=rendered)


def _wrap_with_field(rendered: str, ns: NamedSchema, constraints: dict[str, object]) -> str:
    """Build `Annotated[<rendered>, Field(...)]`, splatting description/examples/constraints into Field."""
    args: list[str] = []
    if ns.description:
        args.append(f"description={ns.description!r}")
    if ns.examples:
        args.append(f"examples={ns.examples!r}")
    for k, v in constraints.items():
        args.append(f"{k}={v!r}")
    return f"Annotated[{rendered}, Field({', '.join(args)})]"


def _build_imports(flags: _ModuleImports) -> list[Import | ImportFrom]:
    imports: list[Import | ImportFrom] = []
    typing_imports: list[str] = []
    if flags.annotated:
        typing_imports.append("Annotated")
    if flags.any:
        typing_imports.append("Any")
    if flags.literal:
        typing_imports.append("Literal")
    if typing_imports:
        imports.append(ImportFrom("typing", typing_imports))

    pydantic_imports = ["BaseModel"]
    if flags.config_dict:
        pydantic_imports.append("ConfigDict")
    if flags.field:
        pydantic_imports.append("Field")
    if flags.discriminator:
        pydantic_imports.append("Discriminator")
        pydantic_imports.append("Tag")
    imports.append(ImportFrom("pydantic", pydantic_imports))
    return imports


class _FieldImports:
    __slots__ = ("any", "field", "literal")

    def __init__(self, *, field: bool = False, any_: bool = False, literal: bool = False) -> None:
        self.field = field
        self.any = any_
        self.literal = literal


def _emit_object_fields(obj: ObjectSchema) -> tuple[list[ModelField], _FieldImports]:
    out: list[ModelField] = []
    imports = _FieldImports()
    seen: set[str] = set()
    for f in obj.fields:
        base = field_name(f.name)
        py_name = base
        suffix = 2
        while py_name in seen:
            py_name = f"{base}_{suffix}"
            suffix += 1
        seen.add(py_name)

        type_expr = _render_type(f.schema)
        if "Literal[" in type_expr:
            imports.literal = True
        default = None if f.required else "None"
        if not f.required and not _renders_with_none(f.schema):
            type_expr = f"{type_expr} | None"

        serialization_alias = f.name if py_name != f.name else None
        constraints = f.schema.constraints if isinstance(f.schema, PrimitiveSchema) else {}
        if serialization_alias is not None or f.description or f.examples or constraints:
            imports.field = True

        out.append(
            ModelField(
                name=py_name,
                type_expr=TypeExpr(type_expr),
                required=f.required,
                default=default,
                description=f.description,
                examples=f.examples,
                constraints=constraints,
                serialization_alias=serialization_alias,
            ),
        )

    if obj.additional_properties == "any":
        imports.any = True

    return out, imports


def _renders_with_none(schema: Schema) -> bool:
    """Whether `_render_type(schema)` already produces a type that admits None."""
    if isinstance(schema, PrimitiveSchema):
        return schema.nullable or schema.kind == "null"
    if isinstance(schema, TaggedUnion):
        return schema.nullable or any(_renders_with_none(m) for m in schema.members)
    return getattr(schema, "nullable", False)


def _render_type(schema: Schema) -> str:  # noqa: PLR0911
    if isinstance(schema, PrimitiveSchema):
        if schema.enum_values:
            base = f"Literal[{', '.join(repr(v) for v in schema.enum_values)}]"
        else:
            base = _PRIMITIVE_PY[schema.kind]
        return f"{base} | None" if schema.nullable else base
    if isinstance(schema, ArraySchema):
        inner = _render_type(schema.items)
        out = f"list[{inner}]"
        return f"{out} | None" if schema.nullable else out
    if isinstance(schema, NamedSchemaRef):
        ref = f'"{model_name(schema.name)}"' if schema.recursive else model_name(schema.name)
        return f"{ref} | None" if schema.nullable else ref
    if isinstance(schema, FreeFormSchema):
        return "Any | None" if schema.nullable else "Any"
    if isinstance(schema, ObjectSchema):
        # nested anonymous objects are not common in MVP-friendly specs; fall back to dict
        return "dict[str, Any]"
    if isinstance(schema, TaggedUnion):
        return _render_tagged_union(schema)
    if isinstance(schema, DiscriminatedUnion):
        # Not expected at field-level (always emitted as a TypeAlias); fall back to union of names
        return " | ".join(model_name(ref.name) for ref in schema.mapping.values())
    raise TypeError(f"Unsupported schema for rendering: {schema!r}")


def _render_tagged_union(u: TaggedUnion) -> str:
    members = " | ".join(_render_type(m) for m in u.members)
    return f"{members} | None" if u.nullable else members


def _emit_discriminated_union_alias(name: str, u: DiscriminatedUnion) -> TypeAlias:
    members = " | ".join(f'Annotated[{model_name(ref.name)}, Tag("{tag}")]' for tag, ref in u.mapping.items())
    return TypeAlias(
        name=name,
        value=f'Annotated[{members}, Discriminator("{u.property_name}")]',
    )
