"""Emit the top-level Client that wires sub-clients together."""

from __future__ import annotations

from typing import TYPE_CHECKING

from openapi_pyx.codegen.nodes import Import, ImportFrom, Module, RootClient, SubClientAttr
from openapi_pyx.naming import model_name, module_name

if TYPE_CHECKING:
    from openapi_pyx.ir.document import Document


def emit_root_module(doc: Document) -> Module:
    """Build a Module IR for the top-level Client that wires sub-clients."""
    sub_clients = [
        SubClientAttr(
            attr_name=module_name(t.name),
            cls_name=f"{model_name(t.name)}Client",
            cls_module=f".clients.{module_name(t.name)}",
        )
        for t in doc.tags
    ]
    imports: list[Import | ImportFrom] = [
        Import("httpx"),
        *[ImportFrom(sc.cls_module, [sc.cls_name]) for sc in sub_clients],
    ]

    return Module(
        docstring=f"Top-level client for {doc.title}. Generated by openapi-pyx.",
        imports=imports,
        body=[RootClient(name="Client", sub_clients=sub_clients)],
    )
