"""Emit normalized schemas as Pydantic v2 model declarations."""

from openapi_pyx.codegen.nodes import (
    ImportFrom,
    ModelField,
    Module,
    PydanticModel,
    TypeAlias,
    TypeExpr,
)
from openapi_pyx.ir.schema import (
    ArraySchema,
    DiscriminatedUnion,
    FreeFormSchema,
    NamedSchema,
    NamedSchemaRef,
    ObjectSchema,
    PrimitiveSchema,
    Schema,
    TaggedUnion,
)
from openapi_pyx.naming import field_name, model_name

_PRIMITIVE_PY = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
    "null": "None",
}


def emit_models_module(schemas: list[NamedSchema]) -> Module:
    body: list[object] = []
    field_needed = False
    annotated_needed = False
    discriminator_needed = False
    config_dict_needed = False
    typing_any_needed = False

    for ns in schemas:
        s = ns.schema
        cls_name = model_name(ns.name)

        if isinstance(s, ObjectSchema):
            fields, field_imports = _emit_object_fields(s)
            extra = "allow" if s.additional_properties == "any" else None
            body.append(
                PydanticModel(
                    name=cls_name,
                    fields=fields,
                    docstring=ns.description,
                    extra=extra,
                ),
            )
            field_needed = field_needed or field_imports.field
            typing_any_needed = typing_any_needed or field_imports.any
            config_dict_needed = config_dict_needed or extra is not None
        elif isinstance(s, DiscriminatedUnion):
            body.append(_emit_discriminated_union_alias(cls_name, s))
            annotated_needed = True
            discriminator_needed = True
        elif isinstance(s, TaggedUnion):
            body.append(TypeAlias(name=cls_name, value=_render_tagged_union(s)))
        else:
            body.append(TypeAlias(name=cls_name, value=_render_type(s)))

    imports: list[ImportFrom] = []
    if annotated_needed:
        imports.append(ImportFrom("typing", ["Annotated"]))
    if typing_any_needed:
        imports.append(ImportFrom("typing", ["Any"]))

    pydantic_imports = ["BaseModel"]
    if config_dict_needed:
        pydantic_imports.append("ConfigDict")
    if field_needed:
        pydantic_imports.append("Field")
    if discriminator_needed:
        pydantic_imports.append("Discriminator")
        pydantic_imports.append("Tag")
    imports.append(ImportFrom("pydantic", pydantic_imports))

    return Module(
        docstring="Generated by openapi-pyx. Do not edit by hand.",
        imports=imports,
        body=body,
    )


class _FieldImports:
    __slots__ = ("any", "field")

    def __init__(self, *, field: bool = False, any_: bool = False) -> None:
        self.field = field
        self.any = any_


def _emit_object_fields(obj: ObjectSchema) -> tuple[list[ModelField], _FieldImports]:
    out: list[ModelField] = []
    imports = _FieldImports()
    for f in obj.fields:
        py_name = field_name(f.name)
        type_expr = _render_type(f.schema)
        default = None if f.required else "None"
        # If field is optional and type doesn't already include "None", widen it
        if not f.required and "None" not in type_expr:
            type_expr = f"{type_expr} | None"

        serialization_alias = f.name if py_name != f.name else None
        if serialization_alias is not None:
            imports.field = True

        out.append(
            ModelField(
                name=py_name,
                type_expr=TypeExpr(type_expr),
                required=f.required,
                default=default,
                description=f.description,
                serialization_alias=serialization_alias,
            ),
        )

    if obj.additional_properties == "any":
        imports.any = True

    return out, imports


def _render_type(schema: Schema) -> str:  # noqa: PLR0911
    if isinstance(schema, PrimitiveSchema):
        py = _PRIMITIVE_PY[schema.kind]
        return f"{py} | None" if schema.nullable else py
    if isinstance(schema, ArraySchema):
        inner = _render_type(schema.items)
        out = f"list[{inner}]"
        return f"{out} | None" if schema.nullable else out
    if isinstance(schema, NamedSchemaRef):
        ref = f'"{model_name(schema.name)}"' if schema.recursive else model_name(schema.name)
        return f"{ref} | None" if schema.nullable else ref
    if isinstance(schema, FreeFormSchema):
        return "Any | None" if schema.nullable else "Any"
    if isinstance(schema, ObjectSchema):
        # nested anonymous objects are not common in MVP-friendly specs; fall back to dict
        return "dict[str, Any]"
    if isinstance(schema, TaggedUnion):
        return _render_tagged_union(schema)
    if isinstance(schema, DiscriminatedUnion):
        # Not expected at field-level (always emitted as a TypeAlias); fall back to union of names
        return " | ".join(model_name(ref.name) for ref in schema.mapping.values())
    raise TypeError(f"Unsupported schema for rendering: {schema!r}")


def _render_tagged_union(u: TaggedUnion) -> str:
    members = " | ".join(_render_type(m) for m in u.members)
    return f"{members} | None" if u.nullable else members


def _emit_discriminated_union_alias(name: str, u: DiscriminatedUnion) -> TypeAlias:
    members = " | ".join(f'Annotated[{model_name(ref.name)}, Tag("{tag}")]' for tag, ref in u.mapping.items())
    return TypeAlias(
        name=name,
        value=f'Annotated[{members}, Discriminator("{u.property_name}")]',
    )
