"""Emit per-tag sub-clients."""

from __future__ import annotations

from typing import TYPE_CHECKING

from openapi_pyx.codegen.emit_models import _render_type
from openapi_pyx.codegen.nodes import (
    Assign,
    AsyncMethod,
    ClientClass,
    Import,
    ImportFrom,
    Module,
    Param,
    Stmt,
    TypeExpr,
)
from openapi_pyx.ir.operation import Operation, ParamLocation
from openapi_pyx.ir.schema import (
    ArraySchema,
    DiscriminatedUnion,
    NamedSchemaRef,
    ObjectSchema,
    Schema,
    TaggedUnion,
)
from openapi_pyx.naming import method_name, model_name

if TYPE_CHECKING:
    from openapi_pyx.ir.document import TagGroup


def emit_client_module(group: TagGroup) -> Module:
    """Build a Module IR for the given tag group."""
    methods = [_emit_method(op) for op in group.operations]

    referenced_models = sorted(_collect_model_refs(group.operations))

    body: list[Stmt] = []
    # Per-response TypeAdapter pre-instantiated at module scope.
    adapter_targets = sorted({m.response_type.rendered for m in methods if m.response_type})
    for tgt in adapter_targets:
        safe = "".join(c if c.isalnum() else "_" for c in tgt)
        body.append(Assign(target=f"_Adapter_{safe}", value=f"TypeAdapter({tgt})"))

    body.append(ClientClass(name=f"{_tag_class_prefix(group.name)}Client", methods=methods))

    imports: list[Import | ImportFrom] = [
        Import("httpx"),
        ImportFrom("pydantic", ["TypeAdapter"]),
    ]
    if referenced_models:
        imports.append(ImportFrom("..models", referenced_models))

    return Module(
        docstring=f"{group.name} sub-client. Generated by openapi-pyx.",
        imports=imports,
        body=body,
    )


def _tag_class_prefix(tag: str) -> str:
    return model_name(tag)


def _emit_method(op: Operation) -> AsyncMethod:
    py_method_name = method_name(op.operation_id)
    query_params: list[tuple[str, str]] = []
    path_params: list[tuple[str, str]] = []
    header_params: list[tuple[str, str]] = []
    sig_params: list[Param] = [Param("self")]

    for p in op.parameters:
        local = method_name(p.name)
        type_expr = _render_param_type(p.schema, optional=not p.required)
        default = None if p.required else "None"
        sig_params.append(Param(local, TypeExpr(type_expr), default=default, keyword_only=True))
        if p.location is ParamLocation.QUERY:
            query_params.append((p.name, local))
        elif p.location is ParamLocation.PATH:
            path_params.append((p.name, local))
        elif p.location is ParamLocation.HEADER:
            header_params.append((p.name, local))

    body_param: str | None = None
    body_required = True  # Default True; only relevant when body_param is set
    if op.request_body is not None:
        body_required = op.request_body.required
        body_type = _render_param_type(op.request_body.schema, optional=not body_required)
        body_default = None if body_required else "None"
        sig_params.append(Param("body", TypeExpr(body_type), default=body_default, keyword_only=True))
        body_param = "body"

    response_type: TypeExpr | None = None
    return_type: TypeExpr | None = None
    if op.response is not None:
        rendered = _render_param_type(op.response.schema, optional=False)
        response_type = TypeExpr(rendered)
        return_type = TypeExpr(rendered)

    return AsyncMethod(
        name=py_method_name,
        params=sig_params,
        return_type=return_type,
        http_method=op.http_method,
        url_template=op.path,
        query_params=query_params,
        path_params=path_params,
        header_params=header_params,
        body_param=body_param,
        body_required=body_required,
        response_type=response_type,
        docstring=op.summary,
    )


def _render_param_type(schema: Schema, *, optional: bool) -> str:
    rendered = _render_type(schema)
    if optional and "None" not in rendered:
        return f"{rendered} | None"
    return rendered


def _collect_model_refs(ops: list[Operation]) -> set[str]:  # noqa: C901
    out: set[str] = set()

    def walk(s: Schema) -> None:
        if isinstance(s, NamedSchemaRef):
            out.add(model_name(s.name))
        elif isinstance(s, ArraySchema):
            walk(s.items)
        elif isinstance(s, ObjectSchema):
            for f in s.fields:
                walk(f.schema)
        elif isinstance(s, TaggedUnion):
            for m in s.members:
                walk(m)
        elif isinstance(s, DiscriminatedUnion):
            for ref in s.mapping.values():
                walk(ref)

    for op in ops:
        for p in op.parameters:
            walk(p.schema)
        if op.request_body is not None:
            walk(op.request_body.schema)
        if op.response is not None:
            walk(op.response.schema)
    return out
