# generated by datamodel-codegen:
#   filename:  primitives.yaml

from pydantic import BaseModel, ConfigDict


class Atoms(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    s: str
    i: int
    n: float | None = None
    b: bool | None = None
    opt_s: str | None = None
