"""Generated by openapi-pyx. Do not edit by hand."""

from pydantic import BaseModel


class Atoms(BaseModel):
    s: str
    i: int
    n: float | None = None
    b: bool | None = None
    opt_s: str | None = None
