# generated by datamodel-codegen:
#   filename:  sanitized_field.yaml

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Item(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    class_: Annotated[str, Field(alias="class")]
    for_: Annotated[int | None, Field(alias="for")] = None
