"""Generated by openapi-pyx. Do not edit by hand."""

from pydantic import BaseModel, ConfigDict, Field


class Item(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    class_: str = Field(alias="class")
    for_: int | None = Field(None, alias="for")
