"""things sub-client. Generated by openapi-pyx."""

import httpx
from pydantic import TypeAdapter

from ..models import Thing

_Adapter_Thing = TypeAdapter(Thing)


class ThingsClient:
    def __init__(self, http: httpx.AsyncClient) -> None:
        self._http = http

    async def list_things(self) -> Thing:
        resp = await self._http.get("/things")
        resp.raise_for_status()
        return _Adapter_Thing.validate_json(resp.content)
