"""pets sub-client. Generated by openapi-pyx."""

import httpx
from pydantic import TypeAdapter

from ..models import Pet, Pets

_Adapter_Pet = TypeAdapter(Pet)


_Adapter_Pets = TypeAdapter(Pets)


class PetsClient:
    def __init__(self, http: httpx.AsyncClient) -> None:
        self._http = http

    async def list_pets(self, *, limit: int | None = None) -> Pets:
        """List all pets"""
        params: dict[str, object] = {}
        if limit is not None:
            params["limit"] = limit
        resp = await self._http.get("/pets", params=params)
        resp.raise_for_status()
        return _Adapter_Pets.validate_json(resp.content)

    async def create_pet(self, *, body: Pet) -> None:
        """Create a pet"""
        headers = {"Content-Type": "application/json"}
        resp = await self._http.post(
            "/pets",
            headers=headers,
            content=body.model_dump_json(by_alias=True, exclude_none=True),
        )
        resp.raise_for_status()
        return None

    async def show_pet_by_id(self, *, pet_id: str) -> Pet:
        """Info for a specific pet"""
        resp = await self._http.get(f"/pets/{pet_id}")
        resp.raise_for_status()
        return _Adapter_Pet.validate_json(resp.content)
