from openapi_pyx.codegen.nodes import (
    Import,
    ImportFrom,
    ModelField,
    Module,
    PydanticModel,
    TypeExpr,
)
from openapi_pyx.codegen.render import render_module


def test_render_module_emits_docstring_and_imports():
    mod = Module(
        docstring="Generated by openapi-pyx.",
        imports=[Import("httpx"), ImportFrom("pydantic", ["BaseModel", "Field"])],
        body=[],
    )
    src = render_module(mod)
    assert src.startswith('"""Generated by openapi-pyx."""')
    assert "import httpx" in src
    assert "from pydantic import BaseModel, Field" in src


def test_render_pydantic_model_with_required_and_optional_fields():
    mod = Module(
        docstring=None,
        imports=[ImportFrom("pydantic", ["BaseModel"])],
        body=[
            PydanticModel(
                name="Pet",
                fields=[
                    ModelField(name="id", type_expr=TypeExpr("int"), required=True),
                    ModelField(
                        name="name",
                        type_expr=TypeExpr("str | None"),
                        required=False,
                        default="None",
                    ),
                ],
            ),
        ],
    )
    src = render_module(mod)
    assert "class Pet(BaseModel):" in src
    assert "    id: int" in src
    assert "    name: str | None = None" in src


def test_render_field_with_serialization_alias():
    mod = Module(
        docstring=None,
        imports=[ImportFrom("pydantic", ["BaseModel", "Field"])],
        body=[
            PydanticModel(
                name="X",
                fields=[
                    ModelField(
                        name="x_id",
                        type_expr=TypeExpr("int"),
                        required=True,
                        serialization_alias="x-id",
                    ),
                ],
            ),
        ],
    )
    src = render_module(mod)
    assert 'Field(alias="x-id")' in src or 'alias="x-id"' in src
