from openapi_pyx.codegen.nodes import (
    Import,
    ImportFrom,
    ModelField,
    Module,
    PydanticModel,
    TypeExpr,
)
from openapi_pyx.codegen.render import render_module


def test_render_module_emits_docstring_and_imports():
    mod = Module(
        docstring="Generated by openapi-pyx.",
        imports=[Import("httpx"), ImportFrom("pydantic", ["BaseModel", "Field"])],
        body=[],
    )
    src = render_module(mod)
    assert src.startswith('"""Generated by openapi-pyx."""')
    assert "import httpx" in src
    assert "from pydantic import BaseModel, Field" in src


def test_render_pydantic_model_with_required_and_optional_fields():
    mod = Module(
        docstring=None,
        imports=[ImportFrom("pydantic", ["BaseModel"])],
        body=[
            PydanticModel(
                name="Pet",
                fields=[
                    ModelField(name="id", type_expr=TypeExpr("int"), required=True),
                    ModelField(
                        name="name",
                        type_expr=TypeExpr("str | None"),
                        required=False,
                        default="None",
                    ),
                ],
            ),
        ],
    )
    src = render_module(mod)
    assert "class Pet(BaseModel):" in src
    assert "    id: int" in src
    assert "    name: str | None = None" in src


def test_render_pydantic_model_with_extra_emits_configdict():
    mod = Module(
        docstring=None,
        imports=[ImportFrom("pydantic", ["BaseModel", "ConfigDict"])],
        body=[
            PydanticModel(
                name="OpenBag",
                fields=[ModelField(name="id", type_expr=TypeExpr("int"), required=True)],
                extra="allow",
            ),
        ],
    )
    src = render_module(mod)
    assert 'model_config = ConfigDict(extra="allow")' in src


def test_render_field_with_serialization_alias():
    mod = Module(
        docstring=None,
        imports=[ImportFrom("pydantic", ["BaseModel", "Field"])],
        body=[
            PydanticModel(
                name="X",
                fields=[
                    ModelField(
                        name="x_id",
                        type_expr=TypeExpr("int"),
                        required=True,
                        serialization_alias="x-id",
                    ),
                ],
            ),
        ],
    )
    src = render_module(mod)
    assert 'Field(alias="x-id")' in src or 'alias="x-id"' in src


def test_render_field_with_description_emits_field_call():
    mod = Module(
        docstring=None,
        imports=[ImportFrom("pydantic", ["BaseModel", "Field"])],
        body=[
            PydanticModel(
                name="Pet",
                fields=[
                    ModelField(
                        name="id",
                        type_expr=TypeExpr("int"),
                        required=True,
                        description="Stable pet identifier.",
                    ),
                ],
            ),
        ],
    )
    src = render_module(mod)
    assert "Field(description='Stable pet identifier.')" in src


def test_render_field_combines_default_alias_and_description():
    mod = Module(
        docstring=None,
        imports=[ImportFrom("pydantic", ["BaseModel", "Field"])],
        body=[
            PydanticModel(
                name="X",
                fields=[
                    ModelField(
                        name="x_id",
                        type_expr=TypeExpr("int | None"),
                        required=False,
                        default="None",
                        serialization_alias="x-id",
                        description="External id.",
                    ),
                ],
            ),
        ],
    )
    src = render_module(mod)
    assert "Field(None, alias=\"x-id\", description='External id.')" in src


def test_render_multi_line_docstring_uses_pep257_layout():
    mod = Module(
        docstring="Summary line.\n\nLonger description spanning\nmultiple lines.",
        imports=[],
        body=[],
    )
    src = render_module(mod)
    assert '"""Summary line.\n' in src
    assert "Longer description spanning" in src
    assert "multiple lines." in src
    assert src.count('"""') == 2  # exactly one opening, one closing
