# generated by datamodel-codegen:
#   filename:  recursive_mutual.yaml

from pydantic import BaseModel, ConfigDict


class A(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    b: B | None = None


class B(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    a: A | None = None


A.model_rebuild()
