"""Generated by openapi-pyx. Do not edit by hand."""

from pydantic import BaseModel


class Foo(BaseModel):
    a: str | None = None


class Bar(BaseModel):
    b: int | None = None


Either = Foo | Bar
