# generated by datamodel-codegen:
#   filename:  oneof_no_discriminator.yaml

from pydantic import BaseModel, ConfigDict


class Foo(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    a: str | None = None


class Bar(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    b: int | None = None


type Either = Foo | Bar
