# generated by datamodel-codegen:
#   filename:  recursive_self.yaml

from pydantic import BaseModel, ConfigDict


class Node(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: str
    next: Node | None = None


Node.model_rebuild()
