# generated by datamodel-codegen:
#   filename:  allof_compose.yaml

from pydantic import BaseModel, ConfigDict


class Base(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: int


class Named(Base):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
