"""Generated by openapi-pyx. Do not edit by hand."""

from typing import Annotated

from pydantic import BaseModel, Discriminator, Tag


class Dog(BaseModel):
    kind: str
    bark: str


class Cat(BaseModel):
    kind: str
    meow: str


Animal = Annotated[
    Annotated[Dog, Tag("dog")] | Annotated[Cat, Tag("cat")], Discriminator("kind")
]
