# generated by datamodel-codegen:
#   filename:  oneof_discriminator.yaml

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class Dog(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    kind: Literal["dog"]
    bark: str


class Cat(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    kind: Literal["cat"]
    meow: str


type Animal = Annotated[Dog | Cat, Field(discriminator="kind")]
