# generated by datamodel-codegen:
#   filename:  field_examples.yaml

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Pet(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Annotated[int, Field(examples=[1, 42, 100])]
    name: Annotated[
        str, Field(description="Display name.", examples=["Rex", "Whiskers"])
    ]
    legacy: Annotated[str | None, Field(examples=["legacy-value"])] = None
