"""Generated by openapi-pyx. Do not edit by hand."""

from pydantic import BaseModel, Field


class Pet(BaseModel):
    id: int = Field(examples=[1, 42, 100])
    name: str = Field(description="Display name.", examples=["Rex", "Whiskers"])
    legacy: str | None = Field(None, examples=["legacy-value"])
