# generated by datamodel-codegen:
#   filename:  nullable_array.yaml

from pydantic import BaseModel, ConfigDict


class Bag(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    items: list[str] | None = None
