"""Top-level client for WildcardResp. Generated by openapi-pyx."""

import ssl

import httpx

from .clients.things import ThingsClient


class Client:
    def __init__(
        self,
        base_url: str,
        *,
        http: httpx.AsyncClient | None = None,
        timeout: httpx.Timeout | float | None = None,
        headers: dict[str, str] | None = None,
        cookies: dict[str, str] | None = None,
        verify: bool | str | ssl.SSLContext = True,
        follow_redirects: bool = False,
        httpx_args: dict[str, object] | None = None,
    ) -> None:
        self._http = http or httpx.AsyncClient(
            base_url=base_url,
            timeout=timeout if timeout is not None else httpx.Timeout(5.0),
            headers=headers or {},
            cookies=cookies or {},
            verify=verify,
            follow_redirects=follow_redirects,
            **(httpx_args or {}),
        )
        self.things = ThingsClient(self._http)

    async def __aenter__(self) -> "Client":
        return self

    async def __aexit__(self, *_exc: object) -> None:
        await self._http.aclose()
