"""Top-level client for WildcardResp. Generated by openapi-pyx."""

import httpx

from .clients.things import ThingsClient


class Client:
    def __init__(self, base_url: str, *, http: httpx.AsyncClient | None = None) -> None:
        self._http = http or httpx.AsyncClient(base_url=base_url)
        self.things = ThingsClient(self._http)

    async def __aenter__(self) -> "Client":
        return self

    async def __aexit__(self, *_exc: object) -> None:
        await self._http.aclose()
