# generated by datamodel-codegen:
#   filename:  wildcard_2xx.yaml

from pydantic import BaseModel, ConfigDict


class Thing(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: int
