# generated by datamodel-codegen:
#   filename:  petstore.yaml

from pydantic import BaseModel, ConfigDict


class Pet(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: int
    name: str
    tag: str | None = None


type Pets = list[Pet]
