# generated by datamodel-codegen:
#   filename:  optional_union_with_null.yaml

from pydantic import BaseModel, ConfigDict


class Holder(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    any_of_with_null: str | None = None
