"""pets sub-client. Generated by openapi-pyx."""

from urllib.parse import quote

import httpx
from pydantic import TypeAdapter

from ..models import Pet, Pets
from ..runtime import ApiError, Response

_Adapter_Pet = TypeAdapter(Pet)


_Adapter_Pets = TypeAdapter(Pets)


class PetsClient:
    def __init__(self, http: httpx.Client) -> None:
        self._http = http

    def list_pets(self, *, limit: int | None = None) -> Pets:
        """List all pets"""
        params: dict[str, object] = {}
        if limit is not None:
            params["limit"] = limit
        resp = self._http.get("/pets", params=params)
        if resp.status_code == 200:
            return _Adapter_Pets.validate_json(resp.content)
        parsed: object | None = None
        raise ApiError(resp.status_code, resp.content, dict(resp.headers), parsed)

    def list_pets_detailed(self, *, limit: int | None = None) -> Response[Pets | None]:
        """List all pets"""
        params: dict[str, object] = {}
        if limit is not None:
            params["limit"] = limit
        resp = self._http.get("/pets", params=params)
        parsed: Pets | None = None
        if resp.status_code == 200:
            parsed = _Adapter_Pets.validate_json(resp.content)
        return Response(
            status_code=resp.status_code,
            headers=dict(resp.headers),
            content=resp.content,
            parsed=parsed,
        )

    def create_pet(self, *, body: Pet) -> None:
        """Create a pet"""
        headers = {"Content-Type": "application/json"}
        resp = self._http.post(
            "/pets",
            headers=headers,
            content=_Adapter_Pet.dump_json(body, by_alias=True, exclude_none=True),
        )
        if resp.status_code == 201:
            return None
        parsed: object | None = None
        raise ApiError(resp.status_code, resp.content, dict(resp.headers), parsed)

    def create_pet_detailed(self, *, body: Pet) -> Response[None]:
        """Create a pet"""
        headers = {"Content-Type": "application/json"}
        resp = self._http.post(
            "/pets",
            headers=headers,
            content=_Adapter_Pet.dump_json(body, by_alias=True, exclude_none=True),
        )
        parsed: None = None
        return Response(
            status_code=resp.status_code,
            headers=dict(resp.headers),
            content=resp.content,
            parsed=parsed,
        )

    def show_pet_by_id(self, *, pet_id: str) -> Pet:
        """Info for a specific pet"""
        resp = self._http.get(f"/pets/{quote(str(pet_id), safe='')}")
        if resp.status_code == 200:
            return _Adapter_Pet.validate_json(resp.content)
        parsed: object | None = None
        raise ApiError(resp.status_code, resp.content, dict(resp.headers), parsed)

    def show_pet_by_id_detailed(self, *, pet_id: str) -> Response[Pet | None]:
        """Info for a specific pet"""
        resp = self._http.get(f"/pets/{quote(str(pet_id), safe='')}")
        parsed: Pet | None = None
        if resp.status_code == 200:
            parsed = _Adapter_Pet.validate_json(resp.content)
        return Response(
            status_code=resp.status_code,
            headers=dict(resp.headers),
            content=resp.content,
            parsed=parsed,
        )
